ER図に従ってデータベース定義書を作成し、DDL文を実装
U-11/quelcode-db pull request #2
Opened 2020-11-03 14:37 UTC by U-11

2020-11-04 13:58 UTC, piasoratech requested changes
全体的な指摘
- 作成者idや更新者idも一応外部キーになります。(usersテーブルを参照している)
- DDL文に多くの変更があるため定義書は確認していません。合わせて修正をしてください。
- 全体的に要件と違う部分やtypoが目立ちます。再提出の際にはセルフチェックを忘れずに

2020-11-04 13:58 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +  email VARCHAR(100) NOT NULL UNIQUE,
今回の要件にメールアドレスのユニーク制約は入っていないので、修正しましょう。
間違って入力したメールアドレスの情報が残っている場合に、本当にそのアドレスを使っている人が登録できないなどの事象が発生するからです。

2020-11-04 13:58 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +  phone VARCHAR(13),
この命名から勤務先の電話番号はイメージしにくいので、修正しましょう

2020-11-04 13:58 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +  updated TIMESTAMP NOT NULL
削除フラグ、日時系の命名にはベストプラクティスがあるので調べてみましょう。
また、作成日時と更新日時で型が違うのは何か狙いがあるでしょうか？

2020-11-04 13:58 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +  name VARCHAR(100) NOT NULL UNIQUE,
要件と違う部分があるので修正しましょう

2020-11-04 13:58 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +  description VARCHAR(1000) NOT NULL,
ここも要件と違う部分があります

2020-11-04 13:58 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +  updated_user_id INT(11) NOT NULL
usersテーブルと同じ指摘です

2020-11-04 13:58 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +  join_at DATETIME NOT NULL,
参加"した"日時なので命名を変更しましょう

2020-11-04 13:58 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +  post_user_id INT(11) NOT NULL REFERENCES users(id),
微妙な部分ですが、投稿者idは特別なものではなく他のテーブルでいう作成者idと同じような扱いになります。
なので、命名はcreateを使ったものにするか、投稿日時のほうをpostを使ったものに変えるかのどちらかの対応をお願いします。(要は統一されていればいいです)

2020-11-04 13:58 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +  updated_user_id INT(11) NOT NULL
usersテーブルと同じ指摘です

2020-11-04 13:58 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +  updated_user_id INT(11) NOT NULL
usersテーブルと同じ指摘です

2020-11-04 13:58 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +  personel_id INT(11) NOT NULL REFERENCES users(id),
これは担当者のidでしょうか？
名前から連想できないので、もう一度考えてみましょう

2020-11-04 15:31 UTC, U-11 commented on db/db-challenge2/DDL.sql
> +  email VARCHAR(100) NOT NULL UNIQUE,
UNIQUE制約を削除して訂正しました。
二重登録防止の意図で制約しましたが、間違った登録をする場合を想定していませんでした。

2020-11-04 15:32 UTC, U-11 commented on db/db-challenge2/DDL.sql
> +  phone VARCHAR(13),
「office_telephone」に修正しました。

2020-11-04 15:39 UTC, U-11 commented on db/db-challenge2/DDL.sql
> +  updated TIMESTAMP NOT NULL
命名を「is_deleted」、「created_at」、「updated_at」に修正し、日付の型はDATETIMEに統一ました。
（作成日時と更新日時で型が違うのは、PHPの教材「よくわかるPHPの教科書」で型を使い分けていたことと
こちらのページの解説で「明示的に値が割り当てられていなければ、もっとも新しい変更日時に自動的に設定される。」と記載があったので、DB更新時に指定なしで楽かなと思い深く考えず使い分けました。）

2020-11-04 15:39 UTC, U-11 commented on db/db-challenge2/DDL.sql
> +  name VARCHAR(100) NOT NULL UNIQUE,
UNIQUE制約を削除しました。

2020-11-04 15:40 UTC, U-11 commented on db/db-challenge2/DDL.sql
> +  description VARCHAR(1000) NOT NULL,
descriptionのNOT NULL制約を削除しました。

2020-11-04 15:40 UTC, U-11 commented on db/db-challenge2/DDL.sql
> +  join_at DATETIME NOT NULL,
joined_atに修正しました。

2020-11-04 15:42 UTC, U-11 commented on db/db-challenge2/DDL.sql
> +  post_user_id INT(11) NOT NULL REFERENCES users(id),
post_user_idをcreated_user_idに修正し、表記を統一しました。

2020-11-04 15:43 UTC, U-11 commented on db/db-challenge2/DDL.sql
> +  updated_user_id INT(11) NOT NULL
命名を「is_deleted」、「created_at」、「updated_at」に修正し、日付の型はDATETIMEに統一しました。

2020-11-04 15:43 UTC, U-11 commented on db/db-challenge2/DDL.sql
> +  updated_user_id INT(11) NOT NULL
命名を「is_deleted」、「created_at」、「updated_at」に修正し、日付の型はDATETIMEに統一しました。

2020-11-04 15:44 UTC, U-11 commented on db/db-challenge2/DDL.sql
> +  personel_id INT(11) NOT NULL REFERENCES users(id),
assigned_user_idに修正しました。

2020-11-04 15:45 UTC, U-11 commented
作成者idや更新者idも外部キーに修正しました。
データベース定義書も合わせて修正しました。

2020-11-05 21:24 UTC, choimake approved these changes
LGTMです。次に進んでください。

2020-11-07 12:39 UTC, merged