SQL文を実行しデータを更新及び削除
U-11/quelcode-db pull request #5
Opened 2020-11-09 10:47 UTC by U-11

2020-11-09 11:07 UTC, piasoratech requested changes
コメントしたので確認をお願いします

2020-11-09 11:07 UTC, piasoratech commented on db/db-challenge3/db-011/db-011.sql
> +SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
トランザクションの分離レベルまで意識した書き方ができているのは良いです！
せっかくなのでこの辺も読んでおいてください！
https://qiita.com/song_ss/items/38e514b05e9dabae3bdb

2020-11-09 11:07 UTC, piasoratech commented on db/db-challenge3/db-012/db-012.sql
> +  send_file=1,
Uさんのテーブル定義やdb課題3のNo002を見るとファイル送信が許可されているのはsend_fileが1のときではないでしょうか？

2020-11-09 11:07 UTC, piasoratech commented on db/db-challenge3/db-014/db-014.sql
> +      is_deleted=0
逆じゃないですか？

2020-11-09 12:49 UTC, U-11 commented on db/db-challenge3/db-012/db-012.sql
> +  send_file=1,
定義書及びDDL文を修正し、
send_file=1
がファイル送信許可とし、デフォルト値を1にしました。

2020-11-09 13:06 UTC, U-11 commented on db/db-challenge3/db-014/db-014.sql
> +      is_deleted=0
NOT INを用いた二重否定より可読性を考慮したSQL文に修正いたしました。

2020-11-10 15:30 UTC, U-11 commented
roomsテーブルのカラム名をallow_send_fileに修正したことにより、
関連するSQL文（002、007、012）を修正いたしました。

2020-11-14 05:57 UTC, gacha1987 commented
LGTMです！

2020-11-14 05:59 UTC, merged