チャットルームテーブルの定義書とDDL分の修正
U-11/quelcode-db pull request #6
Opened 2020-11-09 14:25 UTC by U-11

2020-11-09 14:46 UTC, piasoratech requested changes
コメントしたので確認をお願いします。

2020-11-09 14:46 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +  send_file TINYINT(1) DEFAULT 1 NOT NULL,
Slack側で指摘したように「1がファイル送信許可の前提でカラム名を再考する」ことができていないです。
この名前でファイル送信が許可されているのか、許可されていないのかがわからないのでカラム名を見ただけでtrueのときどのような状態なのかが理解できるような名前にする必要があります。

2020-11-10 11:27 UTC, U-11 commented on db/db-challenge2/DDL.sql
> +  send_file TINYINT(1) DEFAULT 1 NOT NULL,
カラム名を再定義しました。

2020-11-10 12:34 UTC, piasoratech requested changes
コメントしたので確認をお願いします

2020-11-10 12:34 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +<<<<<<< Updated upstream
コンフリクトを起こした際の文章が入ってしまっているので、不要な部分は削除してください。

再定義後のカラム名については問題ありません。

2020-11-10 14:01 UTC, piasoratech approved these changes
OKです

2020-11-10 14:06 UTC, merged